services:
  nginx:
    image: nginx:1.26.2
    ports:
      - 8000:80
    volumes:
      - ./src_frontend:/var/www/html/frontend
      - ./src_backend:/var/www/html/backend
      - ./docker/nginx:/etc/nginx/conf.d
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./src_backend:/var/www/html/backend
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8001:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8002:8080
    environment:
      - SWAGGER_JSON=/openapi.yml
    volumes:
      - ./api-docs/openapi.yml:/openapi.yml
volumes:
  mysqldata: